{ config, lib, ... }:
let
  cfg = config.takoeight0821.programs.gemini;

  bashAllowList = [
    "git status"
    "git diff"
    "git log"
    "git show"
    "git branch"
    "git rev-parse"
    "git remote"
    "git stash list"
    "git tag"

    "gh-pr-reply"
    "gh pr view"
    "gh pr list"
    "gh pr diff"
    "gh pr checks"
    "gh issue view"
    "gh issue list"
    "gh repo view"
    "gh api --method GET"
    "gh run view"
    "gh run list"
    "gh run watch"

    "nix build"
    "nix develop"
    "nix run"
    "nix shell"
    "nix flake"
    "nix eval"
    "nix search"
    "nix path-info"
    "nix why-depends"
    "nix log"
    "nix derivation show"
    "nix config show"
    "nix hash"
    "nix registry"
    "nix profile list"
    "nix profile diff-closures"
    "nix profile history"
    "nix store cat"
    "nix store diff-closures"
    "nix store dump-path"
    "nix store ls"
    "nix store path-info"
    "nix fmt"
    "nixfmt"
    "nix help"
    "nix repl"
    "nix-env --query"
    "nix-env -q"
    "nix-env --list-generations"

    "brew list"
    "brew info"
    "brew search"

    "cat"
    "head"
    "tail"
    "echo"
    "ls"
    "pwd"
    "dirname"
    "basename"
    "realpath"
    "type"

    "jq"
    "rg"
    "grep"
    "diff"
    "uniq"
    "tr"
    "cut"
    "sed"
    "find"
    "fd"
    "sort"

    "file"
    "stat"
    "tree"
    "du"
    "df"

    "date"
    "printenv"
    "uname"

    "ghq list"
    "code"
    "which"
    "wc"
    "delta"
    "tmux"
  ];

  mkRule = cmd: ''
    [[rule]]
    toolName = "run_shell_command"
    commandPrefix = "${cmd}"
    decision = "allow"
    priority = 100
  '';

  policyToml = ''
    # Auto-generated by nix-home-modules/modules/home/gemini-policies.nix
    # Edit bashAllowList in the .nix source instead of editing this file.

  ''
  + lib.concatMapStringsSep "\n" mkRule bashAllowList;
in
{
  config = lib.mkIf cfg.enable {
    home.file.".gemini/policies/auto-approve.toml".text = policyToml;
  };
}
