{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.takoeight0821.programs.neovim;
in
{
  options.takoeight0821.programs.neovim = {
    enable = lib.mkEnableOption "Neovim configuration";
  };

  config = lib.mkIf cfg.enable {
    programs.neovim = {
      enable = true;
      defaultEditor = true;
      viAlias = true;
      vimAlias = true;
      withRuby = false;
      withPython3 = false;

      # LSP servers, formatters and search tools are provided by Nix (pinned via
      # flake.lock) instead of being fetched at runtime by mason. This removes the
      # runtime binary-download attack surface.
      extraPackages = with pkgs; [
        lua-language-server # lua_ls
        fsautocomplete # F# LSP (self-contained, bundles dotnet runtime)
        stylua # lua formatter (used by conform)
        ripgrep # telescope live_grep
        fd # telescope find_files
      ];

      # Plugins are pinned by nixpkgs/flake.lock and placed on the packpath at build
      # time. No runtime git cloning, no auto-update. Plugin-specific setup goes in
      # per-plugin `config` (home-manager guarantees it runs after the plugin loads);
      # global config lives in the lua modules required from extraLuaConfig.
      plugins = with pkgs.vimPlugins; [
        {
          plugin = vscode-nvim;
          type = "lua";
          config = "vim.cmd([[colorscheme vscode]])";
        }

        # Treesitter parsers + queries are built by Nix; native vim.treesitter.start()
        # (registered in autocmds.lua) enables highlighting. No :TSUpdate at runtime.
        nvim-treesitter.withAllGrammars

        plenary-nvim # telescope dependency
        telescope-nvim # keymaps defined in keymaps.lua (command-style)

        {
          plugin = conform-nvim;
          type = "lua";
          config = ''
            require("conform").setup({
              notify_on_error = false,
              format_on_save = function(bufnr)
                local disable_filetypes = { c = true, cpp = true }
                return {
                  timeout_ms = 500,
                  lsp_fallback = not disable_filetypes[vim.bo[bufnr].filetype],
                }
              end,
              formatters_by_ft = {
                lua = { "stylua" },
              },
            })
          '';
        }

        {
          plugin = Ionide-vim;
          type = "lua";
          config = ''
            -- Disable Ionide's built-in LSP since we use fsautocomplete via vim.lsp.config
            vim.g["fsharp#lsp_auto_setup"] = 0
            vim.g["fsharp#lsp_recommended_colorscheme"] = 0
            vim.g["fsharp#fsi_command"] = "dotnet fsi"
            -- "none" disables Ionide's default FSI keybindings; we map them below
            -- via <Plug> ourselves. ("custom" would require fsi_keymap_send/toggle.)
            vim.g["fsharp#fsi_keymap"] = "none"

            -- F# Interactive keybindings (set on FileType, so leader is already defined)
            vim.api.nvim_create_autocmd("FileType", {
              pattern = { "fsharp", "fs", "fsx", "fsi" },
              callback = function()
                local opts = { buffer = true, silent = true }
                vim.keymap.set("n", "<leader>fi", "<Plug>(fsharp-send-line)", opts)
                vim.keymap.set("v", "<leader>fi", "<Plug>(fsharp-send-selection)", opts)
                vim.keymap.set("n", "<leader>ft", "<cmd>FsiShow<cr>", { buffer = true, desc = "Toggle F# Interactive" })
                vim.keymap.set("n", "<leader>fr", "<cmd>FsiReset<cr>", { buffer = true, desc = "Reset F# Interactive" })
              end,
            })
          '';
        }
      ];

      # init.lua entry point. Generated by home-manager from this content + the
      # per-plugin configs above. Leader is set before any leader-dependent keymaps
      # are loaded (keymaps.lua).
      extraLuaConfig = ''
        if vim.g.vscode then
          -- VSCode extension
          -- https://github.com/vscode-neovim/vscode-neovim/issues/298
          vim.opt.clipboard:append("unnamedplus")
          return
        end

        vim.g.mapleader = " "
        vim.g.maplocalleader = "\\"

        require("config.options")
        require("config.keymaps")
        require("config.autocmds")
        require("config.lsp")
      '';
    };

    xdg.configFile = {
      "nvim/lua/config/options.lua".text = ''
        -- Set options
        local opt = vim.opt

        -- Line numbers
        opt.number = true
        opt.relativenumber = false

        -- Tabs and indentation
        opt.tabstop = 2
        opt.shiftwidth = 2
        opt.expandtab = true
        opt.autoindent = true

        -- Line wrapping
        opt.wrap = true
        opt.linebreak = true
        opt.breakindent = true

        -- Search settings
        opt.ignorecase = true
        opt.smartcase = true

        -- Cursor line
        opt.cursorline = true

        -- Appearance
        opt.termguicolors = true
        opt.signcolumn = "yes"

        -- Backspace
        opt.backspace = "indent,eol,start"

        -- Clipboard
        opt.clipboard:append("unnamedplus")

        -- Split windows
        opt.splitright = true
        opt.splitbelow = true

        -- Consider - as part of word
        opt.iskeyword:append("-")

        -- Disable swapfile
        opt.swapfile = false

        -- Enable mouse
        opt.mouse = "a"

        -- Set completeopt for better completion experience
        opt.completeopt = "menu,menuone,noselect"

        -- Persistent undo
        opt.undofile = true

        -- Interval for writing swap file to disk, also used by gitsigns
        opt.updatetime = 250

        -- Set timeout for mapped sequences
        opt.timeoutlen = 300
      '';

      "nvim/lua/config/keymaps.lua".text = ''
        -- Set keymaps
        local keymap = vim.keymap

        -- Clear search highlights
        keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")

        -- Delete without yanking
        keymap.set("n", "x", '"_x')

        -- Increment/decrement numbers
        keymap.set("n", "+", "<C-a>")
        keymap.set("n", "-", "<C-x>")

        -- Window management
        keymap.set("n", "<leader>sv", "<C-w>v", { desc = "Split window vertically" })
        keymap.set("n", "<leader>sh", "<C-w>s", { desc = "Split window horizontally" })
        keymap.set("n", "<leader>se", "<C-w>=", { desc = "Make splits equal size" })
        keymap.set("n", "<leader>sx", "<cmd>close<CR>", { desc = "Close current split" })

        -- Tab management
        keymap.set("n", "<leader>to", "<cmd>tabnew<CR>", { desc = "Open new tab" })
        keymap.set("n", "<leader>tx", "<cmd>tabclose<CR>", { desc = "Close current tab" })
        keymap.set("n", "<leader>tn", "<cmd>tabn<CR>", { desc = "Go to next tab" })
        keymap.set("n", "<leader>tp", "<cmd>tabp<CR>", { desc = "Go to previous tab" })
        keymap.set("n", "<leader>tf", "<cmd>tabnew %<CR>", { desc = "Open current buffer in new tab" })

        -- Navigate buffers
        keymap.set("n", "<S-l>", "<cmd>bnext<CR>", { desc = "Next buffer" })
        keymap.set("n", "<S-h>", "<cmd>bprevious<CR>", { desc = "Previous buffer" })

        -- Stay in indent mode
        keymap.set("v", "<", "<gv", { desc = "Indent left and reselect" })
        keymap.set("v", ">", ">gv", { desc = "Indent right and reselect" })

        -- Move text up and down
        keymap.set("v", "J", ":m '>+1<CR>gv=gv", { desc = "Move text down" })
        keymap.set("v", "K", ":m '<-2<CR>gv=gv", { desc = "Move text up" })

        -- Better paste
        keymap.set("v", "p", '"_dP', { desc = "Paste without yanking" })

        -- File explorer (built-in netrw, replaces neo-tree)
        keymap.set("n", "<leader>fe", "<cmd>Lexplore<CR>", { desc = "Toggle file explorer (netrw)" })

        -- Telescope (fuzzy finding)
        keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find files" })
        keymap.set("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", { desc = "Live grep" })
        keymap.set("n", "<leader>fb", "<cmd>Telescope buffers<CR>", { desc = "Buffers" })
        keymap.set("n", "<leader>fh", "<cmd>Telescope help_tags<CR>", { desc = "Help tags" })

        -- Format buffer (conform)
        keymap.set({ "n", "v" }, "<leader>f", function()
          require("conform").format({ async = true, lsp_fallback = true })
        end, { desc = "[F]ormat buffer" })

        -- Diagnostics (built-in vim.diagnostic, replaces trouble)
        keymap.set("n", "[d", vim.diagnostic.goto_prev, { desc = "Go to previous diagnostic" })
        keymap.set("n", "]d", vim.diagnostic.goto_next, { desc = "Go to next diagnostic" })
        keymap.set("n", "<leader>e", vim.diagnostic.open_float, { desc = "Show diagnostic error messages" })
        keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostics list (loclist)" })
        keymap.set("n", "<leader>xx", function()
          vim.diagnostic.setqflist()
        end, { desc = "Diagnostics (quickfix)" })
        keymap.set("n", "<leader>xX", function()
          vim.diagnostic.setloclist()
        end, { desc = "Buffer diagnostics (loclist)" })

        -- Native completion (pum) navigation/confirm
        keymap.set("i", "<CR>", function()
          return vim.fn.pumvisible() == 1 and "<C-y>" or "<CR>"
        end, { expr = true, desc = "Confirm completion or newline" })
        keymap.set("i", "<Tab>", function()
          return vim.fn.pumvisible() == 1 and "<C-n>" or "<Tab>"
        end, { expr = true })
        keymap.set("i", "<S-Tab>", function()
          return vim.fn.pumvisible() == 1 and "<C-p>" or "<S-Tab>"
        end, { expr = true })
      '';

      "nvim/lua/config/autocmds.lua".text = ''
        local autocmd = vim.api.nvim_create_autocmd
        local augroup = vim.api.nvim_create_augroup

        -- Highlight on yank
        autocmd("TextYankPost", {
          group = augroup("highlight_yank", { clear = true }),
          callback = function()
            vim.highlight.on_yank()
          end,
        })

        -- Enable treesitter highlighting (parsers provided by Nix via withAllGrammars)
        autocmd("FileType", {
          group = augroup("treesitter_start", { clear = true }),
          callback = function()
            pcall(vim.treesitter.start)
          end,
        })

        -- Resize splits if window got resized
        autocmd({ "VimResized" }, {
          group = augroup("resize_splits", { clear = true }),
          callback = function()
            local current_tab = vim.fn.tabpagenr()
            vim.cmd("tabdo wincmd =")
            vim.cmd("tabnext " .. current_tab)
          end,
        })

        -- Close some filetypes with <q>
        autocmd("FileType", {
          group = augroup("close_with_q", { clear = true }),
          pattern = {
            "help",
            "lspinfo",
            "man",
            "qf",
            "checkhealth",
          },
          callback = function(event)
            vim.bo[event.buf].buflisted = false
            vim.keymap.set("n", "q", "<cmd>close<cr>", { buffer = event.buf, silent = true })
          end,
        })

        -- Auto create dir when saving a file, in case some intermediate directory does not exist
        autocmd({ "BufWritePre" }, {
          group = augroup("auto_create_dir", { clear = true }),
          callback = function(event)
            if event.match:match("^%w%w+://") then
              return
            end
            local file = vim.loop.fs_realpath(event.match) or event.match
            vim.fn.mkdir(vim.fn.fnamemodify(file, ":p:h"), "p")
          end,
        })

        -- Disable line numbers for certain filetypes
        autocmd("FileType", {
          group = augroup("disable_line_numbers", { clear = true }),
          pattern = { "help", "qf", "netrw", "checkhealth", "lspinfo", "man" },
          callback = function()
            vim.opt_local.number = false
            vim.opt_local.relativenumber = false
          end,
        })
      '';

      "nvim/lua/config/lsp.lua".text = ''
        -- Native LSP configuration (Neovim 0.11+). Servers are provided on PATH by Nix
        -- (extraPackages); no mason, no nvim-lspconfig.

        vim.lsp.config("lua_ls", {
          cmd = { "lua-language-server" },
          filetypes = { "lua" },
          root_markers = { ".luarc.json", ".luarc.jsonc", ".git" },
          settings = {
            Lua = {
              completion = {
                callSnippet = "Replace",
              },
              -- Recognize the `vim` global (replaces neodev)
              diagnostics = {
                globals = { "vim" },
              },
            },
          },
        })

        vim.lsp.config("fsautocomplete", {
          cmd = { "fsautocomplete", "--adaptive-lsp-server-enabled" },
          filetypes = { "fsharp" },
          root_markers = { "*.sln", "*.fsproj", ".git" },
          settings = {
            FSharp = {
              keywordsAutocomplete = true,
              ExternalAutocomplete = false,
              Linter = true,
              UnionCaseStubGeneration = true,
              UnionCaseStubGenerationBody = 'failwith "Not Implemented"',
              RecordStubGeneration = true,
              RecordStubGenerationBody = 'failwith "Not Implemented"',
              InterfaceStubGeneration = true,
              InterfaceStubGenerationObjectIdentifier = "this",
              InterfaceStubGenerationMethodBody = 'failwith "Not Implemented"',
              UnusedOpensAnalyzer = true,
              UnusedDeclarationsAnalyzer = true,
              UseSdkScripts = true,
              SimplifyNameAnalyzer = true,
              ResolveNamespaces = true,
              EnableReferenceCodeLens = true,
            },
          },
        })

        vim.lsp.enable({ "lua_ls", "fsautocomplete" })

        -- LSP keymaps and native completion on attach
        vim.api.nvim_create_autocmd("LspAttach", {
          group = vim.api.nvim_create_augroup("user-lsp-attach", { clear = true }),
          callback = function(event)
            local map = function(keys, func, desc)
              vim.keymap.set("n", keys, func, { buffer = event.buf, desc = "LSP: " .. desc })
            end

            local builtin = require("telescope.builtin")
            map("gd", builtin.lsp_definitions, "[G]oto [D]efinition")
            map("gr", builtin.lsp_references, "[G]oto [R]eferences")
            map("gI", builtin.lsp_implementations, "[G]oto [I]mplementation")
            map("<leader>D", builtin.lsp_type_definitions, "Type [D]efinition")
            map("<leader>ds", builtin.lsp_document_symbols, "[D]ocument [S]ymbols")
            map("<leader>ws", builtin.lsp_dynamic_workspace_symbols, "[W]orkspace [S]ymbols")
            map("<leader>rn", vim.lsp.buf.rename, "[R]e[n]ame")
            map("<leader>ca", vim.lsp.buf.code_action, "[C]ode [A]ction")
            map("K", vim.lsp.buf.hover, "Hover Documentation")
            map("gD", vim.lsp.buf.declaration, "[G]oto [D]eclaration")

            local client = vim.lsp.get_client_by_id(event.data.client_id)

            -- Native autocompletion (replaces nvim-cmp)
            if client and client:supports_method("textDocument/completion") then
              vim.lsp.completion.enable(true, client.id, event.buf, { autotrigger = true })
            end

            -- Highlight references of the word under cursor
            if client and client.server_capabilities.documentHighlightProvider then
              local highlight_augroup = vim.api.nvim_create_augroup("user-lsp-highlight", { clear = false })
              vim.api.nvim_create_autocmd({ "CursorHold", "CursorHoldI" }, {
                buffer = event.buf,
                group = highlight_augroup,
                callback = vim.lsp.buf.document_highlight,
              })
              vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI" }, {
                buffer = event.buf,
                group = highlight_augroup,
                callback = vim.lsp.buf.clear_references,
              })
            end

            -- Toggle inlay hints
            if client and client:supports_method("textDocument/inlayHint") and vim.lsp.inlay_hint then
              map("<leader>th", function()
                vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = event.buf }), { bufnr = event.buf })
              end, "[T]oggle Inlay [H]ints")
            end
          end,
        })
      '';
    };
  };
}
